config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/preferences", to: "pages#preferences", as: :preferences
  get "/preferences/movies", to: "pages#movies", as: :preferences_movies


  resources :movie_watchlists, only: [:index, :show, :create, :destroy]
  get 'details', to: 'pages#details'
end

app/views/shared/_appear_1.html.erb
<div class="title">
  <p><strong><%= @result[0]["title"] %></strong></p>
</div>
<div class="rating">
  <p><i class="fa-solid fa-star text-warning"></i> <%= @result[0]["vote_average"] %>/10</p>
</div>
<div class="description">
  <p><%= @result[0]["overview"] %></p>
</div>
<div class="d-flex button-gap mt-3">
  <div class="button-get-started"></div>
  <div class="button-get-started"></div>
</div>
<div>
</div>

app/views/shared/_appear_2.html.erb
<div class="title">
  <p><strong><%= @result[1]["title"] %></strong></p>
</div>
<div class="rating">
  <p><i class="fa-solid fa-star text-warning"></i> <%= @result[1]["vote_average"] %>/10</p>
</div>
<div class="description">
  <p><%= @result[1]["overview"] %></p>
</div>
<div class="d-flex button-gap mt-3">
  <div class="button-get-started"></div>
  <div class="button-get-started"></div>
</div>
<div>
</div>

app/views/shared/_appear_3.html.erb
<div class="title">
  <p><strong><%= @result[2]["title"] %></strong></p>
</div>
<div class="rating">
  <p><i class="fa-solid fa-star text-warning"></i> <%= @result[1]["vote_average"] %>/10</p>
</div>
<div class="description">
  <p><%= @result[2]["overview"] %></p>
</div>
<div class="d-flex button-gap mt-3">
  <div class="button-get-started"></div>
  <div class="button-get-started"></div>
</div>
<div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_menubar.html.erb
<div class="mobile-nav">
  <%= link_to root_path, class: "icon-white" do %>
    <i class="fa-solid fa-house"></i>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to edit_user_registration_path, class: "icon-white" do %>
      <i class="fa-solid fa-user"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "icon-white" do %>
      <i class="fa-solid fa-user"></i>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to movie_watchlists_path, class: "icon-white" do %>
      <i class="fa-solid fa-bars"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "icon-white" do %>
      <i class="fa-solid fa-bars"></i>
    <% end %>
  <% end %>
  <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "icon-white" do %>
    <i class="fa-solid fa-arrow-right-from-bracket"></i>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <button id="navbarToggle" class="navbar-toggler" type="button" aria-expanded="false">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  </div>
</div>

app/views/shared/_popup_1.html.erb
<div class="d-none play-button" data-toggle-target="play1Element">
  <div class="play-button" data-bs-toggle="modal" data-bs-target="#exampleModal1">
    <i class="fa-solid fa-play"></i>
  </div>
  <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content background-pop mx-3 d-flex flex-column align-items-center">
        <div class="d-flex justify-content-center mt-4">
          <p class="modal-title fs-5" id="exampleModalLabel">Watch this program on:</p>
          <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>
        </div>
        <div class="modal-body mt-5 d-flex justify-content-center stream-body">
          <% @result_link_movie[0]["results"][@country]["flatrate"].each do |flats| %>
            <% @streaming_services.each do |streaming_service| %>
              <% if (streaming_service.source_id == flats["provider_id"]) %>
                <%= link_to @result_link_movie[0]["results"][@country]["link"], target: "_blank" do %>
                  <%= image_tag("https://image.tmdb.org/t/p/w200#{flats["logo_path"]}", alt: flats["provider_name"]) %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_popup_2.html.erb
<div class="d-none play-button" data-toggle-target="play2Element">
  <div class="play-button" data-bs-toggle="modal" data-bs-target="#exampleModal2">
    <i class="fa-solid fa-play"></i>
  </div>
  <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content background-pop mx-3 d-flex flex-column align-items-center">
        <div class="d-flex justify-content-center mt-4">
          <p class="modal-title fs-5" id="exampleModalLabel">Watch this program on:</p>
          <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>
        </div>
        <div class="modal-body mt-5 d-flex justify-content-center stream-body">
          <% @result_link_movie[1]["results"][@country]["flatrate"].each do |flats| %>
            <% @streaming_services.each do |streaming_service| %>
              <% if (streaming_service.source_id == flats["provider_id"]) %>
                <%= link_to @result_link_movie[1]["results"][@country]["link"], target: "_blank" do %>
                  <%= image_tag("https://image.tmdb.org/t/p/w200#{flats["logo_path"]}", alt: flats["provider_name"]) %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_popup_3.html.erb
<div class="d-none play-button" data-toggle-target="play3Element">
  <div class="play-button" data-bs-toggle="modal" data-bs-target="#exampleModal3">
    <i class="fa-solid fa-play"></i>
  </div>
  <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel3" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content background-pop mx-3 d-flex flex-column align-items-center">
        <div class="d-flex justify-content-center mt-4">
          <p class="modal-title fs-5" id="exampleModalLabel">Watch this program on:</p>
          <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>
        </div>
        <div class="modal-body mt-5 d-flex justify-content-center stream-body">
          <% @result_link_movie[2]["results"][@country]["flatrate"].each do |flats| %>
            <% @streaming_services.each do |streaming_service| %>
              <% if (streaming_service.source_id == flats["provider_id"]) %>
                <%= link_to @result_link_movie[2]["results"][@country]["link"], target: "_blank" do %>
                  <%= image_tag("https://image.tmdb.org/t/p/w200#{flats["logo_path"]}", alt: flats["provider_name"]) %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>