config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/preferences", to: "pages#preferences", as: :preferences
  get "/preferences/movies", to: "pages#movies", as: :preferences_movies


  resources :movie_watchlists, only: [:index, :show, :create, :destroy]
  get 'details', to: 'pages#details'
end

app/views/pages/_details_one.html.erb
  <div class="top-image" style="background-image: url('https://image.tmdb.org/t/p/original<%= movie["backdrop_path"] %>')">
    <!-- Placeholder for the image -->
  </div>
  <div class="details-page">

    <div class="info-section">
      <div class="row justify-content-between">
        <div class="col-4 title-section align-items-start">
          <p class="movie-title "><%= movie["title"] %></p>
          <div class="d-flex d-block gap-1" >
            <p><%= Date.parse(movie["release_date"]).year %></p>
            <p>-</p>
            <p><%= movie["runtime"] %></p>
            <p>min</p>
          </div>
          <div class="d-flex gap-5 providers justify-content-start">
            <p>WATCH ON:</p>
            <%= render "pages/streaming_links", watch_providers: movie["watch_providers"] %>
          </div>
        </div>


        <div class="col-4" style="font-size: 85%;">
          <p><i class="fa-solid fa-star text-warning"></i> <%= movie["vote_average"] %><strong>/10</strong></p>

        </div>

        <div class="col-4">
          <div class="movie-card" style="background-image: url('https://image.tmdb.org/t/p/original<%= movie["poster_path"] %>')">
            <!-- Placeholder for the movie card -->
          </div>
        </div>
      </div>
    </div>


    <div class="overviews">
      <p><strong>Overview:  </strong><%= movie["overview"] %></p>
    </div>


    <iframe src="https://www.youtube.com/embed/<%= movie["trailer_youtube_key"] %>?playsinline=1" width="320" height="180" style="z-index=1000;"></iframe>
    <div class="d-flex text-center flex-column mt-4 mb-5">

      <%= turbo_frame_tag "movie_#{movie["tmdb_id"]}" do %>
        <%= render "pages/movie_watchlist_button", movie: movie, is_in_watchlist: is_in_watchlist %>
      <% end %>

    </div>

  </div>

app/views/pages/_movie_watchlist_button.html.erb
<% if is_in_watchlist %>
  <%= link_to movie_watchlist_path(movie[:id]), data: { turbo_method: :delete } do %>
    <button class="btn btn-danger">Remove from watchlist</button>
  <% end %>
<% else %>
  <%= simple_form_for MovieWatchlist.new do |f| %>
    <%= f.input :title, as: :hidden, input_html: { value: movie["title"] } %>
    <%= f.input :overview, as: :hidden, input_html: { value: movie["overview"] } %>
    <%= f.input :release_date, as: :hidden, input_html: { value: movie["release_date"] } %>
    <%= f.input :poster_path, as: :hidden, input_html: { value: movie["poster_path"] } %>
    <%= f.input :backdrop_path, as: :hidden, input_html: { value: movie["backdrop_path"] } %>
    <%= f.input :tmdb_id, as: :hidden, input_html: { value: movie["tmdb_id"] } %>
    <%= f.input :vote_average, as: :hidden, input_html: { value: movie["vote_average"] } %>
    <%= f.input :runtime, as: :hidden, input_html: { value: movie["runtime"] } %>
    <%= f.input :trailer_youtube_key, as: :hidden, input_html: { value: movie["trailer_youtube_key"] } %>
    <%= f.input :watch_providers, as: :hidden, input_html: { value: movie["watch_providers"].to_json } %>
    <%= f.submit "ADD TO WATCHLIST", class: "btn add-to-watchlist-button" %>
  <% end %>
<% end %>

app/views/pages/_result_movie.html.erb
<div
    class="d-flex justify-content-center px-3 image-alone"
    data-controller="result-movie"
    data-result-movie-hide-class="d-none"
>
    <div class="row justify-content-center movie-info mb-3 d-flex">
      <div class="movie-card col-4" data-action="click->result-movie#toggle" style="background-image:url('https://image.tmdb.org/t/p/original<%= result["poster_path"] %>')"></div>
    </div>
    <div class="d-none infos d-flex flex-column align-items-start col-8" data-result-movie-target="infos">
        <div class="title">
            <p><strong><%= result["title"] %></strong></p>
        </div>
        <div class="rating">
            <p><i class="fa-solid fa-star text-warning"></i> <%= result["vote_average"] %>/10</p>
        </div>
        <%# <div class="description">
            <p></p>
        </div> %>
        <div class="d-flex button-gap">
            <button class="btn watch-button" type="button" data-bs-toggle="modal" data-bs-target="#watch-<%= result["tmdb_id"] %>">WATCH</button>
            <button class="btn details-button" type="button" data-bs-toggle="modal" data-bs-target="#movie-<%= result["tmdb_id"] %>">DETAILS</button>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" id="movie-<%= result["tmdb_id"] %>" aria-labelledby="details" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "details_one", movie: result, is_in_watchlist: false %>
      </div>
      <div class="modal-footer d-flex justify-content-center">

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="watch-<%= result["tmdb_id"] %>" tabindex="-1" aria-labelledby="watch" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content background-pop mx-3 d-flex flex-column align-items-center">
      <div class="d-flex justify-content-center mt-4">
        <p class="modal-title fs-5">Watch this program on:</p>
      </div>
      <div class="modal-body mt-5 d-flex justify-content-center stream-body">
        <%= render "streaming_links", watch_providers: result["watch_providers"] %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_streaming_links.html.erb
 <% watch_providers.each do |provider| %>
  <%= link_to provider["streaming_link"], target: "_blank" do %>
    <%= image_tag(provider["logo_path"]) %>
  <% end %>
<% end %>

app/views/pages/details.html.erb
 <div class="details-page">
    <div class="top-image">
      <!-- Placeholder for the image -->
    </div>

    <div class="info-section">
      <div class="row">
        <div class="col left-column">
          <p class="movie-title">Title</p>
          <p>Year and runtime</p>
          <p>genre</p>
        </div>


        <div class="col middle-column">
          <p>Rating: 5/10</p>
        </div>

        <div class="col right-column">
          <div class="movie-card">
            <!-- Placeholder for the movie card -->
          </div>
        </div>
      </div>
    </div>


    <div class="movie-description-section">
      <p><strong>Description:</strong>description</p>
    </div>


    <div class="add-to-watchlist-container">
      <button class="add-to-watchlist-button">Add to Watchlist</button>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="top-image">
  <div class="header-text">
    <h1>Welcome to Filmdash</h1>
    <h2>Your cinematic journey!</h2>
  </div>
  <%= image_tag "home_page/Chaplin.webp", alt: "Charlie Chaplin" %>
  <div class="get-started-button">
    <%= link_to "Get started", preferences_path, class: "button-get-started" %>
  </div>
</div>
<div class="bottom-image">
  <%= image_tag "home_page/Truffaut.jpg", alt: "François Truffaut" %>
</div>

app/views/pages/movies.html.erb
<div style="position:relative;">
  <h1 style="text-align: center; padding-top: 25px; padding-bottom: 10px;">Your Selection!</h1>

  <div class="d-flex flex-column align-items-center my-4">
    <% if @results.length < 3 %>
      <h1>No result</h1>
    <% else %>
      <% @results.each do |movie_result| %>
        <%= render "result_movie", result: movie_result %>
      <% end %>
    <% end %>
    <div class="generate-button-container">
      <div class="generate-button">
        <button data-action="click->toggle#refresh" class="button-get-started">Give me new choices</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/preferences.html.erb
<div class= "banner d-flex justify-content-center text-center align-items-center">
  <h2>Select your <br />preferences</h2>
</div>


<%= form_with url: preferences_movies_path, class: "form-height", method: :get do |f| %>
    <div class="section marge-t">
      <h5>Format</h5>
      <div class="d-flex scrolling">
        <div class="radio-space" id="movie-image">
          <%= f.radio_button :format, "movie", id: 'movie' %>
          <%= f.label :format, "Movies", for: "movie" %>
        </div>
        <div class="radio-space" id="serie-img">
          <%= f.radio_button :format, "tv_series", id: 'tv_series' %>
          <%= f.label :format, "Series", for: "tv_series" %>
        </div>
      </div>
    </div>

    <div class="section mt-4 marge-t-two">
      <h5>Runtime</h5>
      <div class="d-flex scrolling">
        <div class="radio-space" id="onehour-img">
          <%= f.radio_button :runtime, "90", id: '90' %>
          <%= f.label :runtime, "1h30 Max", for: "90" %>
        </div>
        <div class="radio-space" id="twohour-img">
          <%= f.radio_button :runtime, "120", id: '120' %>
          <%= f.label :runtime, "2h Max", for: "120" %>
        </div>
        <div class="radio-space" id="threehour-img">
          <%= f.radio_button :runtime, "180", id: '180' %>
          <%= f.label :format, "3h max", for: "120" %>
        </div>
        <div class="radio-space" id="fourhour-img">
          <%= f.radio_button :runtime, "240", id: '240' %>
          <%= f.label :format, "3h and more", for: "240" %>
        </div>
      </div>
    </div>

    <div class="section mt-4 marge-t-two">
      <h5>Genre</h5>
      <div class="d-flex scrolling">
        <div class="radio-space" id="action-img">
          <%= f.radio_button :genre, "28", id: '28' %>
          <%= f.label :genre, "Action", for: "28" %>
        </div>
        <div class="radio-space" id="adventure-img">
          <%= f.radio_button :genre, "12", id: "12" %>
          <%= f.label :genre, "Adventure", for: "12" %>
        </div>
        <div class="radio-space" id="animation-img">
          <%= f.radio_button :genre, "16", id: '16' %>
          <%= f.label :genre, "Animation", for: "16" %>
        </div>
        <div class="radio-space" id="comedy-img">
          <%= f.radio_button :genre, "35", id: '35' %>
          <%= f.label :genre, "Comedy", for: "35" %>
        </div>
        <div class="radio-space" id="crime-img">
          <%= f.radio_button :genre, "80", id: '80' %>
          <%= f.label :genre, "Crime", for: "80" %>
        </div>
        <div class="radio-space" id="docu-img">
          <%= f.radio_button :genre, "99", id: '99' %>
          <%= f.label :genre, "Documentary", for: "99" %>
        </div>
        <div class="radio-space" id="drama-img">
          <%= f.radio_button :genre, "18", id: '18' %>
          <%= f.label :genre, "Drama", for: "18" %>
        </div>
        <div class="radio-space" id="family-img">
          <%= f.radio_button :genre, "10751", id: '10751' %>
          <%= f.label :genre, "Family", for: "10751" %>
        </div>
        <div class="radio-space" id="fantasy-img">
          <%= f.radio_button :genre, "14", id: '14' %>
          <%= f.label :genre, "Fantasy", for: "14" %>
        </div>
        <div class="radio-space" id="history-img">
          <%= f.radio_button :genre, "36", id: '36' %>
          <%= f.label :genre, "History", for: "36" %>
        </div>
        <div class="radio-space" id="horror-img">
          <%= f.radio_button :genre, "27", id: '27' %>
          <%= f.label :genre, "Horror", for: "27" %>
        </div>
        <div class="radio-space" id="music-img">
          <%= f.radio_button :genre, "10402", id: '10402' %>
          <%= f.label :genre, "Music", for: "10402" %>
        </div>
        <div class="radio-space" id="mystery-img">
          <%= f.radio_button :genre, "9648", id: '9648' %>
          <%= f.label :genre, "Mystery", for: "9648" %>
        </div>
        <div class="radio-space" id="romance-img">
          <%= f.radio_button :genre, "10749", id: '10749' %>
          <%= f.label :genre, "Romance", for: "10749" %>
        </div>
        <div class="radio-space" id="science-img">
          <%= f.radio_button :genre, "878", id: '878' %>
          <%= f.label :genre, "Science Fiction", for: "878" %>
        </div>
        <div class="radio-space" id="thriller-img">
          <%= f.radio_button :genre, "53", id: '53' %>
          <%= f.label :genre, "Thriller", for: "53" %>
        </div>
        <div class="radio-space" id="war-img">
          <%= f.radio_button :genre, "10752", id: '10752' %>
          <%= f.label :genre, "War", for: "10752" %>
        </div>
        <div class="radio-space" id="western-img">
          <%= f.radio_button :genre, "37", id: '37' %>
          <%= f.label :genre, "Western", for: "37" %>
        </div>
      </div>
    </div>

    <div class="section mt-4 marge-t-two">
      <h5>Period</h5>
      <div class="d-flex scrolling">
        <div class="radio-space" id="thisyear-img">
          <%= f.radio_button :period, "2024-01-01", id: '2024-01-01' %>
          <%= f.label :period, "This year", for: "2024-01-01" %>
        </div>
        <div class="radio-space" id="twenty-twenty-img">
          <%= f.radio_button :period, "2020-01-01", id: '2020-01-01' %>
          <%= f.label :period, "2020's", for: "2020-01-01" %>
        </div>
        <div class="radio-space" id="twenty-ten-img">
          <%= f.radio_button :period, "2010-01-01", id: '2010-01-01' %>
          <%= f.label :period, "2010's", for: "2010-01-01" %>
        </div>
        <div class="radio-space" id="twenty-img">
          <%= f.radio_button :period, "2000-01-01", id: '2000-01-01' %>
          <%= f.label :period, "2000's", for: "2000-01-01" %>
        </div>
        <div class="radio-space" id="nine-nine-img">
          <%= f.radio_button :period, "1990-01-01", id: '1990-01-01' %>
          <%= f.label :period, "1990's", for: "1990-01-01" %>
        </div>
        <div class="radio-space" id="nine-eight-img">
          <%= f.radio_button :period, "1980-01-01", id: '1980-01-01' %>
          <%= f.label :period, "1980's", for: "1980-01-01" %>
        </div>
        <div class="radio-space" id="nine-seven-img">
          <%= f.radio_button :period, "1970-01-01", id: '1970-01-01' %>
          <%= f.label :period, "1970's", for: "1970-01-01" %>
        </div>
        <div class="radio-space" id="nine-six-img">
          <%= f.radio_button :period, "1960-01-01", id: '1960-01-01' %>
          <%= f.label :period, "1960's", for: "1960-01-01" %>
        </div>
        <div class="radio-space" id="nine-five-img">
          <%= f.radio_button :period, "1950-01-01", id: '1950-01-01' %>
          <%= f.label :period, "1950's", for: "1950-01-01" %>
        </div>
        <div class="radio-space" id="nine-four-img">
          <%= f.radio_button :period, "1940-01-01", id: '1940-01-01' %>
          <%= f.label :period, "1940's", for: "1940-01-01" %>
        </div>
        <div class="radio-space" id="nine-three-img">
          <%= f.radio_button :period, "1930-01-01", id: '1930-01-01' %>
          <%= f.label :period, "1930's", for: "1930-01-01" %>
        </div>
        <div class="radio-space" id="nine-two-img">
          <%= f.radio_button :period, "1920-01-01", id: '1920-01-01' %>
          <%= f.label :period, "1920's", for: "1920-01-01" %>
        </div>
      </div>
    </div>

    <div class="text-center mt-4 form-submit">
      <%= f.submit "See my selection", class: "stylish-button" %>
    </div>
<% end %>
  <%# <div class="container mt-4">
    <h5>Format</h5>
  </div> %>
<script>
  const images = document.querySelectorAll(".radio-space");
  // console.log(images);

  for (let  i = 0; i < images.length; i++) {
    images[i].onclick = function(e) {
      e.preventDefault();
      // console.log(e);
      const id = this.firstElementChild;
      console.log(id)
      // id.checked = !id.checked
      id.checked = true
      const children = this.parentElement.children
      console.log(children)
      for (let j = 0; j < children.length; j++) {
        if (id.checked === false) {
          children[j].classList.remove("d-none")
          children[j].classList.add("border")
          children[j].classList.add("border-danger")
          // children[j].parentElement.classList.remove("justify-content-center")
          continue
        }

        if (this === children[j]) {
          children[j].classList.remove("d-none")
          children[j].classList.add("border")
          children[j].classList.add("border-danger")
          // children[j].parentElement.classList.add("justify-content-center")
        }
        else {
          children[j].classList.toggle("d-none")
          children[j].classList.remove("border")
          children[j].classList.remove("border-danger")
        }

      }

    }
  }

</script>